# Deployment da aplicação web conversao-peso
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-peso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conversao-peso
  template:
    metadata:
      labels:
        app: conversao-peso
    spec:
      containers:
      - name: conversao-peso
        image: joellgarcia/conversao-peso:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
# Service da aplicação web conversao-peso
apiVersion: v1
kind: Service
metadata:
  name: conversao-peso
spec:
  selector:
    app: conversao-peso
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
  type: LoadBalancer